CREATE TABLE `T5022` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '视频上传自增ID',
  `F02` int(10) NOT NULL DEFAULT '0' COMMENT '置顶值',
  `F03` varchar(50) NOT NULL COMMENT '视频上传标题',
  `F04` varchar(250) DEFAULT NULL COMMENT '文件名称',
  `F05` varchar(50) NOT NULL COMMENT '文件大小',
  `F06` varchar(20) NOT NULL COMMENT '文件格式',
  `F07` enum('YFB','WFB') NOT NULL DEFAULT 'WFB' COMMENT '发布状态,WFB:未发布;YFB:已发布;',
  `F08` int(1) NOT NULL DEFAULT '0' COMMENT '是否自动播放',
   `F09` int(10) NOT NULL COMMENT '创建者,参考T7010.F01',
  `F10` datetime NOT NULL COMMENT '上传时间',
  `F11` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
  PRIMARY KEY (`F01`),
  KEY `F09` (`F09`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COMMENT='视频管理';