CREATE TABLE S50.`T5021` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` varchar(50) NOT NULL,
  `F03` enum('YFB','WFB') NOT NULL DEFAULT 'WFB',
  `F04` varchar(50) DEFAULT NULL,
  `F05` int(10) NOT NULL,
  `F06` datetime NOT NULL,
  `F07` datetime DEFAULT NULL,
  `F08` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `F09` enum('ZCYDL','ZHYAQ','TZYHK','CZYTX') NOT NULL DEFAULT 'CZYTX',
  PRIMARY KEY (`F01`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;