ALTER TABLE `S71`.`T7101`
MODIFY COLUMN `F02`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '前台页头LOGO文件编码' AFTER `F01`,
ADD COLUMN `F12`  varchar(20) NULL COMMENT '前台页尾LOGO文件编码' AFTER `F11`;