-- 初始化常量部分

DELETE FROM S10._1010;
INSERT INTO S10._1010 VALUES('URL.USER_CHARGE','${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/user/fuyou/charge.html','URL','用户充值链接地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.ESCROW_URL_WITHDRAW','${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/pay/fuyou/fyouWithdraw.htm','URL','第三方托管，提现') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('SYSTEM.ESCROW_PREFIX','FUYOU','SYSTEM','托管前缀') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.ESCROW_URL_EXCHANGE','${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/pay/fuyou/fyouBidExchange.htm','URL','第三方托管，债权转让');
INSERT INTO S10._1010 VALUES('URL.ESCROW_URL_RESETMOBILE', '${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/user/fuyou/fyouPhoneUpdate.htm', 'URL', '第三方托管，手机号码修改') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.LOAN_URL','/console/fuyou/fyouLoan.htm','URL','满标放款地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.NOTLOAN_URL','/console/fuyou/fyouNotLoan.htm','URL','满标不放款地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.PAY_PAYMENT_URL','/pay/fuyou/fyouPayment.htm','URL','手动还款地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.PAY_PREPAYMENT_URL','/pay/fuyou/fyouPrepayment.htm','URL','提前还款地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.PAY_SBDF_URL','/pay/fuyou/fyouSbdf.htm','URL','机构垫付地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.PTADVANCE_URL','/console/fuyou/fyouSbdf.htm','URL','平台垫付地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.CHECKYESXXCZ_URL','/console/fuyou/fyouXxczshtg.htm','URL','线下充值审核通过地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.CWGL_MENU_PAGE','/WEB-INF/include/menu/fuyou/cwgl.jsp','URL','财务管理菜单页面路径') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.CARD_MANAGE','/user/fuyou/bankcardlist.html','URL','银行卡管理') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.PAY_BID_URL_4_GYB','${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/pay/fuyou/fyouDonationBid.htm','URL','公益标投标入口地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.ESCROW_URL_USERREGISTER','${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/user/fuyou/fyouUserRegister.htm','URL','第三方托管，用户注册地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.PAY_CHARGE','${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/pay/fuyou/fyouCharge.htm','URL','充值地址入口') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.PAY_BID_URL','${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/pay/fuyou/fyouBid.htm','URL','投标入口地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.PAY_PAYMENTONE_URL','/pay/fuyou/fyouPayment.htm','URL','还款明细中手动还款地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.USER_WITHDRAW','${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/user/fuyou/withdraw.html','URL','用户提现链接地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.OPEN_ESCROW_GUIDE','${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/user/fuyou/openEscrowGuide.htm','URL','托管开户引导页面地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('URL.PAYBADCLAIM_URL','${SYSTEM.SITE_REQUEST_PROTOCOL}${SYSTEM.SITE_DOMAIN}/user/fuyou/fyouPayBadClaim.htm','URL','不良债权购买地址') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('SYSTEM.THIRD_DOMAIN','www-1.fuiou.com','SYSTEM','第三方域名') ON DUPLICATE KEY UPDATE F02 = VALUES(F02);
INSERT INTO S10._1010 VALUES('SYSTEM.SFZJTG','true','SYSTEM','是否开启资金托管, true(开启),false(关闭)');