DROP TABLE IF EXISTS `S61`.`T6114_EXT`;
CREATE TABLE `S61`.`T6114_EXT` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `F02` int(10) NOT NULL COMMENT '用户银行卡ID-T6114',
  `F03` int(10) NOT NULL COMMENT '用户ID-T6110',
  `F04` enum('DTJ','YTJ','CG','SB') NOT NULL DEFAULT 'DTJ' COMMENT '状态,DTJ:待提交;YTJ:已提交;CG:成功;SB:失败;',
  `F05` datetime NOT NULL COMMENT '申请时间',
  `F06` datetime DEFAULT NULL COMMENT '提交时间',
  `F07` datetime DEFAULT NULL COMMENT '完成时间',
  `F08` varchar(30) NOT NULL COMMENT '流水号',
  `F09` varchar(50) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`F01`),
  KEY `F08` (`F08`) USING BTREE,
  KEY `F03` (`F03`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='更换银行卡申请记录';
