DROP TABLE IF EXISTS `S61`.`T6114_EXT`;
CREATE TABLE `S61`.`T6114_EXT` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` int(10) NOT NULL,
  `F03` int(10) NOT NULL,
  `F04` enum('DTJ','YTJ','CG','SB') NOT NULL DEFAULT 'DTJ',
  `F05` datetime NOT NULL,
  `F06` datetime DEFAULT NULL,
  `F07` datetime DEFAULT NULL,
  `F08` varchar(30) NOT NULL,
  `F09` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`F01`),
  KEY `F08` (`F08`) USING BTREE,
  KEY `F03` (`F03`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
