ALTER TABLE `S50`.`T5012`
ADD COLUMN `F11`  enum('TY','QY') NOT NULL DEFAULT 'QY' COMMENT '状态,QY:启用;TY:停用';

ALTER TABLE `S50`.`T5012`
MODIFY COLUMN `F06`  varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '客服号码' ;

ALTER TABLE `S50`.`T5012`
MODIFY COLUMN `F03`  enum('YX','DH','QQ_QY','QQ') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'QQ' COMMENT '客服类型,QQ:QQ;DH:电话号码;YX:邮箱;QQ_QY:企业QQ';

