DROP TABLE IF EXISTS `S50`.`T5017`;
CREATE TABLE `S50`.`T5017` (
  `F01` enum('ZCXY','TFJKXY','FFJKXY','ZQZRXY','GYJZXY','GRXXCQSQTK','QYXXCJSQTK') NOT NULL COMMENT '协议类型,ZCXY:注册协议;TFJKXY:三方借款协议;FFJKXY:四方借款协议;ZQZRXY:债权转让协议;GYJZXY:公益捐助协议;GRXXCQSQTK:个人信息采集授权条款;QYXXCJSQTK:企业信息采集授权条款;',
  `F02` text NOT NULL COMMENT '协议内容',
  `F03` int(10) DEFAULT '0' COMMENT '修改者,参考T7011.F01',
  `F04` timestamp COMMENT '最后修改时间',
  `F05` enum('QY','TY') NOT NULL DEFAULT 'QY' COMMENT '状态,QY:启用;TY:停用;',
  PRIMARY KEY (`F01`),
  KEY `F04` (`F04`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='协议条款';


INSERT INTO `S50`.`T5017` VALUES('ZCXY', '', 0,CURRENT_TIMESTAMP(), 'QY');
INSERT INTO `S50`.`T5017` VALUES('TFJKXY', '', 0,CURRENT_TIMESTAMP(), 'QY');
INSERT INTO `S50`.`T5017` VALUES('FFJKXY', '', 0,CURRENT_TIMESTAMP(), 'QY');
INSERT INTO `S50`.`T5017` VALUES('ZQZRXY', '', 0,CURRENT_TIMESTAMP(), 'QY');
INSERT INTO `S50`.`T5017` VALUES('GYJZXY', '', 0,CURRENT_TIMESTAMP(), 'QY');
INSERT INTO `S50`.`T5017` VALUES('GRXXCQSQTK', '', 0,CURRENT_TIMESTAMP(), 'QY');
INSERT INTO `S50`.`T5017` VALUES('QYXXCJSQTK', '', 0,CURRENT_TIMESTAMP(), 'QY');