/*
Navicat MySQL Data Transfer

Source Server         : 标准库-DEVELOPMENT
Source Server Version : 50621
Source Host           : 192.168.0.235:3306
Source Database       : S50

Target Server Type    : MYSQL
Target Server Version : 50621
File Encoding         : 65001

Date: 2014-10-17 15:39:35
*/

SET FOREIGN_KEY_CHECKS=0;



DROP TABLE IF EXISTS `S50`.`T5010`;
CREATE TABLE `S50`.`T5010` (
  `F01` int(10) NOT NULL AUTO_INCREMENT,
  `F02` varchar(20) NOT NULL,
  `F03` varchar(50) NOT NULL,
  `F04` enum('TY','QY') NOT NULL DEFAULT 'QY',
  `F05` int(10) DEFAULT NULL ,
  `F06` varchar(50) DEFAULT NULL ,
  `F07` varchar(50) DEFAULT NULL ,
  PRIMARY KEY (`F01`),
  UNIQUE KEY `F02` (`F02`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `S50`.`T5011`;
CREATE TABLE `S50`.`T5011` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` int(10) NOT NULL DEFAULT '0',
  `F03` int(10) NOT NULL DEFAULT '0',
  `F04` int(11) NOT NULL DEFAULT '1',
  `F05` enum('YFB','WFB') NOT NULL DEFAULT 'WFB',
  `F06` varchar(50) NOT NULL,
  `F07` varchar(50) DEFAULT NULL,
  `F08` varchar(200) DEFAULT NULL,
  `F09` varchar(50) DEFAULT NULL,
  `F10` int(10) NOT NULL,
  `F11` datetime NOT NULL,
  `F12` datetime DEFAULT NULL,
  `F13` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`F01`),
  KEY `F10` (`F10`) USING BTREE,
  KEY `F12` (`F12`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5011_1`;
CREATE TABLE `S50`.`T5011_1` (
  `F01` int(10) unsigned NOT NULL,
  `F02` text,
  PRIMARY KEY (`F01`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5011_2`;
CREATE TABLE `S50`.`T5011_2` (
  `F01` int(10) unsigned NOT NULL,
  `F02` varchar(50) NOT NULL,
  PRIMARY KEY (`F01`,`F02`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5012`;
CREATE TABLE `S50`.`T5012` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` int(10) NOT NULL DEFAULT '0',
  `F03` enum('YX','DH','QQ_QY','QQ') NOT NULL DEFAULT 'QQ',
  `F04` int(10) NOT NULL DEFAULT '1',
  `F05` varchar(50) NOT NULL,
  `F06` varchar(200) NOT NULL,
  `F07` varchar(50) NOT NULL,
  `F08` int(10) NOT NULL,
  `F09` datetime NOT NULL,
  `F10` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `F11`  enum('TY','QY') NOT NULL DEFAULT 'QY',
  PRIMARY KEY (`F01`),
  KEY `F08` (`F08`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5013`;
CREATE TABLE `S50`.`T5013` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` int(10) NOT NULL DEFAULT '0',
  `F03` int(10) NOT NULL DEFAULT '0',
  `F04` varchar(50) NOT NULL,
  `F05` varchar(255) DEFAULT NULL,
  `F06` varchar(50) NOT NULL,
  `F07` varchar(255) DEFAULT NULL,
  `F08` text,
  `F09` int(10) NOT NULL,
  `F10` datetime NOT NULL,
  `F11` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`F01`),
  KEY `F09` (`F09`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5014`;
CREATE TABLE `S50`.`T5014` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` int(10) NOT NULL DEFAULT '0',
  `F03` int(10) NOT NULL DEFAULT '1',
  `F04` varchar(50) NOT NULL,
  `F05` varchar(255) DEFAULT NULL,
  `F06` int(10) NOT NULL,
  `F07` datetime NOT NULL,
  `F08` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`F01`),
  KEY `F06` (`F06`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5015`;
CREATE TABLE `S50`.`T5015` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` enum('HD','XT') NOT NULL DEFAULT 'XT',
  `F03` int(10) NOT NULL DEFAULT '0',
  `F04` enum('YFB','WFB') NOT NULL DEFAULT 'WFB',
  `F05` varchar(50) NOT NULL,
  `F06` text NOT NULL,
  `F07` int(10) NOT NULL,
  `F08` datetime NOT NULL,
  `F09` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`F01`),
  KEY `F07` (`F07`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5016`;
CREATE TABLE `S50`.`T5016` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` int(10) NOT NULL DEFAULT '1',
  `F03` varchar(50) NOT NULL,
  `F04` varchar(250) DEFAULT NULL,
  `F05` varchar(50) NOT NULL,
  `F06` int(10) NOT NULL,
  `F07` datetime NOT NULL,
  `F08` datetime NOT NULL,
  `F09` datetime NOT NULL,
  `F10` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `F11` text ,
  `F12` enum('APP','GYJZ','PC','APPGYJZ') NOT NULL DEFAULT 'PC',
  PRIMARY KEY (`F01`),
  KEY `F06` (`F06`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `S50`.`T5017`;
CREATE TABLE `S50`.`T5017` (
  `F01` enum('ZCXY','TFJKXY','FFJKXY','ZQZRXY','GYJZXY','GRXXCQSQTK','QYXXCJSQTK','FXTSH','BLZQZRXY') NOT NULL,
  `F02` text NOT NULL ,
  `F03` int(10) DEFAULT '0',
  `F04` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `F05` enum('QY','TY') NOT NULL DEFAULT 'QY',
  PRIMARY KEY (`F01`),
  KEY `F04` (`F04`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5017_1`;
CREATE TABLE `S50`.`T5017_1` (
  `F01` enum('ZCXY','BXBZ') NOT NULL,
  `F02` varchar(50) NOT NULL,
  PRIMARY KEY (`F02`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5018`;
CREATE TABLE `S50`.`T5018` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` int(11) NOT NULL DEFAULT '0',
  `F03` enum('YFB','WFB') NOT NULL,
  `F04` int(10) NOT NULL DEFAULT '0',
  `F05` varchar(50) NOT NULL,
  `F06` varchar(50) NOT NULL,
  `F07` int(10) NOT NULL,
  `F08` datetime NOT NULL,
  `F09` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`F01`),
  KEY `F07` (`F07`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5019`;
CREATE TABLE `S50`.`T5019` (
  `F01` mediumint(6) unsigned NOT NULL,
  `F02` tinyint(2) unsigned NOT NULL,
  `F03` tinyint(2) unsigned NOT NULL,
  `F04` tinyint(2) unsigned NOT NULL,
  `F05` char(15) NOT NULL,
  `F06` char(15) DEFAULT NULL,
  `F07` char(15) DEFAULT NULL,
  `F08` char(15) DEFAULT NULL,
  `F09` char(4) DEFAULT NULL,
  `F10` char(5) DEFAULT NULL,
  `F11` enum('SHENG','SHI','XIAN') NOT NULL,
  `F12` char(15) DEFAULT NULL,
  `F13` enum('QY','TY') NOT NULL DEFAULT 'QY',
  PRIMARY KEY (`F01`),
  KEY `F02` (`F02`) USING BTREE,
  KEY `F03` (`F03`) USING BTREE,
  KEY `F04` (`F04`) USING BTREE,
  KEY `F13` (`F13`) USING BTREE,
  KEY `F12` (`F12`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




DROP TABLE IF EXISTS `S50`.`T5020`;
CREATE TABLE `S50`.`T5020` (
  `F01` int(11) NOT NULL AUTO_INCREMENT,
  `F02` varchar(50) NOT NULL,
  `F03` enum('TY','QY') NOT NULL DEFAULT 'QY',
  `F04` varchar(20) NOT NULL,
  PRIMARY KEY (`F01`),
  UNIQUE KEY `F02` (`F02`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `S50`.`T5021`;
CREATE TABLE S50.`T5021` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` varchar(50) NOT NULL,
  `F03` enum('YFB','WFB') NOT NULL DEFAULT 'WFB',
  `F04` varchar(50) DEFAULT NULL,
  `F05` int(10) NOT NULL,
  `F06` datetime NOT NULL,
  `F07` datetime DEFAULT NULL,
  `F08` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `F09` enum('ZCYDL','ZHYAQ','TZYHK','CZYTX') NOT NULL DEFAULT 'CZYTX',
  PRIMARY KEY (`F01`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `S50`.`T5021_1`;
CREATE TABLE S50.`T5021_1` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` int(10) unsigned NOT NULL,
  `F03` enum('YFB','WFB') NOT NULL DEFAULT 'WFB',
  `F04` varchar(50) DEFAULT NULL,
  `F05` int(10) NOT NULL,
  `F06` datetime NOT NULL,
  `F07` datetime DEFAULT NULL,
  `F08` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `F09` varchar(50) DEFAULT NULL,
  `F10` text,
  `F11` enum('ZCYDL','ZHYAQ','TZYHK','CZYTX') NOT NULL DEFAULT 'CZYTX',
  PRIMARY KEY (`F01`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `S50`.`T5022`;
CREATE TABLE `S50`.`T5022` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` int(10) NOT NULL DEFAULT '0',
  `F03` varchar(50) NOT NULL,
  `F04` varchar(250) DEFAULT NULL,
  `F05` varchar(50) NOT NULL,
  `F06` varchar(20) NOT NULL ,
  `F07` enum('YFB','WFB') NOT NULL DEFAULT 'WFB',
  `F08` int(1) NOT NULL DEFAULT '0',
  `F09` int(10) NOT NULL,
  `F10` datetime NOT NULL,
  `F11` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`F01`),
  KEY `F09` (`F09`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;



DROP TABLE IF EXISTS `S50`.`T5023`;
CREATE TABLE `S50`.`T5023` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `F02` enum('CHARGE','WITHDRAW','CHARGELINE') NOT NULL,
  `F03` text ,
  `F04` datetime NOT NULL,
  `F05` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`F01`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

