/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50621
Source Host           : localhost:3306
Source Database       : s66

Target Server Type    : MYSQL
Target Server Version : 50621
File Encoding         : 65001

Date: 2015-10-28 18:48:27
*/


-- ----------------------------
-- Table structure for `T6601`
-- ----------------------------
DROP TABLE IF EXISTS `S66`.`T6601`;
CREATE TABLE `S66`.`T6601` (
  `F01` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `F02` varchar(100) NOT NULL,
  `F03` varchar(300) NOT NULL,
  `F04` varchar(100) NOT NULL,
  `F05` varchar(100) NOT NULL,
  `F06` enum('ENABLE','DISABLE') NOT NULL DEFAULT 'ENABLE',
  `F07` timestamp NULL DEFAULT NULL,
  `F08` timestamp NULL DEFAULT NULL,
  `F09` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `F10` varchar(200) DEFAULT NULL,
  `F11` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`F01`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Table structure for `t6602`
-- ----------------------------
DROP TABLE IF EXISTS `S66`.`T6602`;
CREATE TABLE `S66`.`T6602` (
  `F01` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `F02` int(11) NOT NULL ,
  `F03` text ,
  `F04` datetime NOT NULL,
  PRIMARY KEY (`F01`)
) ENGINE=InnoDB AUTO_INCREMENT=28 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `S66`.`QRTZ_FIRED_TRIGGERS`;
DROP TABLE IF EXISTS `S66`.`QRTZ_PAUSED_TRIGGER_GRPS`;
DROP TABLE IF EXISTS `S66`.`QRTZ_SCHEDULER_STATE`;
DROP TABLE IF EXISTS `S66`.`QRTZ_LOCKS`;
DROP TABLE IF EXISTS `S66`.`QRTZ_SIMPLE_TRIGGERS`;
DROP TABLE IF EXISTS `S66`.`QRTZ_SIMPROP_TRIGGERS`;
DROP TABLE IF EXISTS `S66`.`QRTZ_CRON_TRIGGERS`;
DROP TABLE IF EXISTS `S66`.`QRTZ_BLOB_TRIGGERS`;
DROP TABLE IF EXISTS `S66`.`QRTZ_TRIGGERS`;
DROP TABLE IF EXISTS `S66`.`QRTZ_JOB_DETAILS`;
DROP TABLE IF EXISTS `S66`.`QRTZ_CALENDARS`;


CREATE TABLE `S66`.`QRTZ_JOB_DETAILS`
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    JOB_NAME  VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    JOB_CLASS_NAME   VARCHAR(250) NOT NULL,
    IS_DURABLE VARCHAR(1) NOT NULL,
    IS_NONCONCURRENT VARCHAR(1) NOT NULL,
    IS_UPDATE_DATA VARCHAR(1) NOT NULL,
    REQUESTS_RECOVERY VARCHAR(1) NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
);

CREATE TABLE `S66`.`QRTZ_TRIGGERS`
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    JOB_NAME  VARCHAR(200) NOT NULL,
    JOB_GROUP VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(250) NULL,
    NEXT_FIRE_TIME BIGINT(13) NULL,
    PREV_FIRE_TIME BIGINT(13) NULL,
    PRIORITY INTEGER NULL,
    TRIGGER_STATE VARCHAR(16) NOT NULL,
    TRIGGER_TYPE VARCHAR(8) NOT NULL,
    START_TIME BIGINT(13) NOT NULL,
    END_TIME BIGINT(13) NULL,
    CALENDAR_NAME VARCHAR(200) NULL,
    MISFIRE_INSTR SMALLINT(2) NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,JOB_NAME,JOB_GROUP)
        REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME,JOB_NAME,JOB_GROUP)
);

CREATE TABLE `S66`.`QRTZ_SIMPLE_TRIGGERS`
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    REPEAT_COUNT BIGINT(7) NOT NULL,
    REPEAT_INTERVAL BIGINT(12) NOT NULL,
    TIMES_TRIGGERED BIGINT(10) NOT NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES `S66`.`QRTZ_TRIGGERS`(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE `S66`.`QRTZ_CRON_TRIGGERS`
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    CRON_EXPRESSION VARCHAR(200) NOT NULL,
    TIME_ZONE_ID VARCHAR(80),
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES `S66`.`QRTZ_TRIGGERS`(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE `S66`.`QRTZ_SIMPROP_TRIGGERS`
  (          
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    STR_PROP_1 VARCHAR(512) NULL,
    STR_PROP_2 VARCHAR(512) NULL,
    STR_PROP_3 VARCHAR(512) NULL,
    INT_PROP_1 INT NULL,
    INT_PROP_2 INT NULL,
    LONG_PROP_1 BIGINT NULL,
    LONG_PROP_2 BIGINT NULL,
    DEC_PROP_1 NUMERIC(13,4) NULL,
    DEC_PROP_2 NUMERIC(13,4) NULL,
    BOOL_PROP_1 VARCHAR(1) NULL,
    BOOL_PROP_2 VARCHAR(1) NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP) 
    REFERENCES `S66`.`QRTZ_TRIGGERS`(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE `S66`.`QRTZ_BLOB_TRIGGERS`
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    BLOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
        REFERENCES `S66`.`QRTZ_TRIGGERS`(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
);

CREATE TABLE `S66`.`QRTZ_CALENDARS`
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    CALENDAR_NAME  VARCHAR(200) NOT NULL,
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (SCHED_NAME,CALENDAR_NAME)
);

CREATE TABLE `S66`.`QRTZ_PAUSED_TRIGGER_GRPS`
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    TRIGGER_GROUP  VARCHAR(200) NOT NULL, 
    PRIMARY KEY (SCHED_NAME,TRIGGER_GROUP)
);

CREATE TABLE `S66`.`QRTZ_FIRED_TRIGGERS`
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    ENTRY_ID VARCHAR(95) NOT NULL,
    TRIGGER_NAME VARCHAR(200) NOT NULL,
    TRIGGER_GROUP VARCHAR(200) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    FIRED_TIME BIGINT(13) NOT NULL,
    SCHED_TIME BIGINT(13) NOT NULL,
    PRIORITY INTEGER NOT NULL,
    STATE VARCHAR(16) NOT NULL,
    JOB_NAME VARCHAR(200) NULL,
    JOB_GROUP VARCHAR(200) NULL,
    IS_NONCONCURRENT VARCHAR(1) NULL,
    REQUESTS_RECOVERY VARCHAR(1) NULL,
    PRIMARY KEY (SCHED_NAME,ENTRY_ID)
);

CREATE TABLE `S66`.`QRTZ_SCHEDULER_STATE`
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    INSTANCE_NAME VARCHAR(200) NOT NULL,
    LAST_CHECKIN_TIME BIGINT(13) NOT NULL,
    CHECKIN_INTERVAL BIGINT(13) NOT NULL,
    PRIMARY KEY (SCHED_NAME,INSTANCE_NAME)
);

CREATE TABLE `S66`.`QRTZ_LOCKS`
  (
    SCHED_NAME VARCHAR(120) NOT NULL,
    LOCK_NAME  VARCHAR(40) NOT NULL, 
    PRIMARY KEY (SCHED_NAME,LOCK_NAME)
);

