DROP TABLE IF EXISTS `S50`.`T5023`;
CREATE TABLE `T5023` (
  `F01` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增ID',
  `F02` enum('CHARGE','WITHDRAW','CHARGELINE') NOT NULL COMMENT '类型,CHARGE:充值;WITHDRAW:提现;CHARGELINE:线下充值',
  `F03` text COMMENT '说明内容',
  `F04` datetime NOT NULL COMMENT '创建时间',
  `F05` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',
   PRIMARY KEY (`F01`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='功能说明';