ALTER TABLE `S50`.`T5017`
MODIFY COLUMN `F01`  enum('ZCXY','TFJKXY','FFJKXY','ZQZRXY','BLZQZRXY','GYJZXY','GRXXCQSQTK','QYXXCJSQTK','FXTSH') CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '协议类型,ZCXY:注册协议;TFJKXY:三方借款协议;FFJKXY:四方借款协议;ZQZRXY:债权转让协议;BLZQZRXY:不良债权转让协议;GYJZXY:公益捐助协议;GRXXCQSQTK:个人信息采集授权条款;QYXXCJSQTK:企业信息采集授权条款;FXTSH:风险提示函' FIRST ;

INSERT INTO `S50`.`T5017` VALUES('BLZQZRXY', '', 0,CURRENT_TIMESTAMP(), 'QY');