ALTER TABLE `S62`.`T6231`
ADD COLUMN `F34`  datetime NULL DEFAULT NULL COMMENT '不良债权转让时间' AFTER `F33`;
ALTER TABLE `S62`.`T6231`
ADD COLUMN `F35`  enum('XYD','DBD','HTXZ') NOT NULL DEFAULT 'HTXZ' COMMENT '来源：信用贷、担保贷、后台新增' AFTER `F34`;