DROP TABLE IF EXISTS `S62`.`T6271`;
CREATE TABLE `S62`.`T6271` (
  `F01` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `F02` int(11) DEFAULT NULL COMMENT '用户ID，参考T6110.F01',
  `F03` int(11) DEFAULT NULL COMMENT '标的ID,参考T6230.F01',
  `F04` varchar(32) DEFAULT NULL COMMENT '合同编号',
  `F05` varchar(32) DEFAULT NULL COMMENT '易保全ID',
  `F06` datetime DEFAULT NULL COMMENT '保全时间',
  `F07` enum('WBQ','YBQ') DEFAULT 'WBQ' COMMENT '保全状态：WBQ-未保全，YBQ-已保全',
  `F08` enum('BLZQZRHT','DFHT','ZQZRHT','JKHT') DEFAULT 'JKHT' COMMENT '合同类型：JKHT-借款合同，ZQZRHT-债权转让合同，DFHT-垫付合同，BLZQZRHT-不良债权转让合同',
  `F09` varchar(128) DEFAULT NULL COMMENT '合同本地存储路径',
  `F10` enum('BDFR','DFR','SRR','ZCR','TZR','JKR') DEFAULT NULL COMMENT '用户类型: TZR-投资人，JKR-借款人，ZCR-转出人，SRR-受让人，DFR-垫付人，BDFR-被垫付人',
  `F11` int(11) DEFAULT NULL COMMENT '债权ID,参考T6251.F01',
  `F12` int(11) DEFAULT NULL COMMENT '不良债权ID,参考 T6265.F01',
  `F13` int(11) DEFAULT NULL COMMENT '债权申请ID, 参考T6260.F01',
  `F14` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`F01`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8 COMMENT='合同保全列表';