DROP TABLE IF EXISTS `S62`.`T6272`;
CREATE TABLE `S62`.`T6272` (
`F01`  int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '网签协议ID,自增' ,
`F02`  int(10) UNSIGNED NOT NULL COMMENT '用户ID,参考T6110.F01' ,
`F03`  int(10) UNSIGNED NOT NULL COMMENT '协议版本号,参考T5126.F02' ,
`F04`  varchar(10) DEFAULT NULL COMMENT '保全ID' ,
`F05`  datetime NULL DEFAULT NULL COMMENT '网签时间' ,
`F06`  enum('WBQ','YBQ') CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '保全状态，WBQ:未保全;YBQ:已保全;' ,
`F07`  varchar(128) DEFAULT NULL COMMENT '协议本地存储路径',
`F08` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '协议编号',
PRIMARY KEY (`F01`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
COMMENT='网签协议表'
ROW_FORMAT=COMPACT
;